version: '3.8'

services:
  database:
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  adminer:
    image: adminer:4.8.0
    ports:
      - "80:8080"
    restart: always

volumes:
  db_data: